import {
  ChangeDetectionStrategy,
  Component,
  DOCUMENT,
  DestroyRef,
  ElementRef,
  PLATFORM_ID,
  afterNextRender,
  inject,
  viewChild,
} from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import * as THREE from 'three';

/**
 * The hero object: the mark's own three stones, in three dimensions.
 *
 * The outlines are the exact path data from `web/tools/mark.py` — the same
 * curves as the favicon and the navbar — extruded and bevelled into solids. The
 * landing page's 3D is therefore not decoration bolted on beside the brand; it
 * is the brand, turned round.
 *
 * Scroll is the only transport. Scrolling down lifts the stack apart and turns
 * it; scrolling back puts it together again. On top of that each stone carries a
 * slow drift of its own, which is the one thing here that moves on a timer — the
 * owner's *"some things may move or rotate or animate by it's own"*.
 *
 * This component is reached through a `@defer` block, so three.js lands in its
 * own chunk and a reader who opens a docs page downloads none of it.
 *
 * It gives up quietly and often, which is the point:
 *
 * - **No WebGL** — no context, a blocked canvas, a browser that refuses — and it
 *   renders nothing at all, leaving the composition behind it to stand alone.
 * - **`prefers-reduced-motion`** stops the loop dead. One frame is drawn, in the
 *   assembled pose, and nothing ever moves. A page that is 3D throughout is
 *   exactly the page that makes people ill if this is forgotten.
 * - **Off screen, it stops.** No frames are drawn while the hero is scrolled
 *   past, so the rest of the page costs nothing.
 *
 * It is `aria-hidden` and contains no text. Every word in the hero is real HTML
 * behind it — a canvas is a picture, and a picture cannot be read by a crawler,
 * a model, or a screen reader.
 */
@Component({
  selector: 'app-stones',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<div #host class="h-full w-full" aria-hidden="true"></div>`,
  styles: `
    :host {
      display: block;
      height: 100%;
      width: 100%;
    }
    canvas {
      display: block;
      height: 100%;
      width: 100%;
    }
  `,
})
export class Stones {
  private readonly host = viewChild.required<ElementRef<HTMLDivElement>>('host');
  private readonly document = inject(DOCUMENT);
  private readonly destroyRef = inject(DestroyRef);

  /** Generated by `web/tools/mark.py`. Top, middle, bottom. */
  private static readonly OUTLINES = [
    'M60.52 11.21c0.37 2.87 -3.72 7.12 -8.28 9.63c-4.56 2.50 -12.28 4.85 -19.07 5.40c-6.80 0.55 -16.72 -0.59 -21.70 -2.10c-4.98 -1.50 -7.88 -4.38 -8.18 -6.91c-0.30 -2.53 1.80 -5.95 6.38 -8.28c4.58 -2.33 14.36 -4.83 21.08 -5.72c6.73 -0.88 14.31 -0.92 19.27 0.41c4.96 1.33 10.13 4.70 10.50 7.57z',
    'M62.00 33.89c-0.22 2.57 -5.30 5.17 -10.49 6.76c-5.19 1.59 -13.90 3.22 -20.66 2.76c-6.77 -0.46 -15.20 -3.04 -19.94 -5.49c-4.74 -2.46 -8.77 -6.39 -8.52 -9.24c0.25 -2.85 4.94 -6.50 10.01 -7.86c5.08 -1.37 13.71 -1.07 20.45 -0.33c6.74 0.74 15.15 2.53 20.01 4.77c4.86 2.24 9.37 6.08 9.15 8.64z',
    'M59.51 49.00c0.06 2.78 -1.42 6.80 -5.96 8.76c-4.54 1.96 -14.49 2.77 -21.27 3.02c-6.78 0.25 -14.35 0.11 -19.39 -1.52c-5.05 -1.63 -10.63 -5.53 -10.89 -8.25c-0.26 -2.72 4.39 -5.84 9.30 -8.06c4.91 -2.23 13.19 -4.98 20.17 -5.29c6.98 -0.31 17.03 1.53 21.70 3.42c4.67 1.89 6.27 5.14 6.34 7.92z',
  ];

  constructor() {
    const isBrowser = isPlatformBrowser(inject(PLATFORM_ID));
    afterNextRender(() => {
      if (isBrowser) {
        this.start();
      }
    });
  }

  private start(): void {
    const container = this.host().nativeElement;
    const view = this.document.defaultView;
    if (!view) {
      return;
    }

    let renderer: THREE.WebGLRenderer;
    try {
      renderer = new THREE.WebGLRenderer({
        alpha: true,
        antialias: true,
        powerPreference: 'low-power',
      });
    } catch {
      // No WebGL. The hero is composed to work without this.
      return;
    }
    renderer.setClearAlpha(0);
    renderer.setPixelRatio(Math.min(view.devicePixelRatio || 1, 2));
    container.appendChild(renderer.domElement);

    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(34, 1, 0.1, 100);
    camera.position.set(0, 0, 3.15);

    // Warm key from the upper left, a cool fill opposite so the shadowed side
    // does not go flat black, and a brand-coloured rim that only ever catches
    // the top edges.
    scene.add(new THREE.AmbientLight(0xffffff, 0.3));
    const key = new THREE.DirectionalLight(0xfff2e8, 3.1);
    key.position.set(-2.6, 3.4, 2.8);
    scene.add(key);
    const fill = new THREE.DirectionalLight(0x7d93b5, 0.5);
    fill.position.set(2.8, -1.6, 1.4);
    scene.add(fill);
    const rim = new THREE.PointLight(0xffb494, 5.5, 12, 2);
    rim.position.set(1.9, 2.4, -2.8);
    scene.add(rim);

    const material = new THREE.MeshPhysicalMaterial({
      color: 0xd97757,
      roughness: 0.38,
      metalness: 0.0,
      clearcoat: 0.7,
      clearcoatRoughness: 0.3,
      sheen: 0.3,
      sheenColor: new THREE.Color(0xffd9c6),
    });

    const group = new THREE.Group();
    const stones = Stones.OUTLINES.map((outline, index) => {
      const geometry = new THREE.ExtrudeGeometry(shapeFromPath(outline), {
        depth: 0.13,
        bevelEnabled: true,
        bevelSegments: 6,
        bevelSize: 0.05,
        bevelThickness: 0.05,
        curveSegments: 40,
      });
      geometry.center();
      const mesh = new THREE.Mesh(geometry, material);
      // Stacked as the mark stacks them, and tilted the way the mark tilts them.
      mesh.position.y = (1 - index) * 0.3;
      mesh.rotation.z = [-0.105, 0.087, -0.035][index];
      group.add(mesh);
      return mesh;
    });
    group.rotation.x = -0.5;
    scene.add(group);

    const resize = () => {
      const { clientWidth, clientHeight } = container;
      if (clientWidth === 0 || clientHeight === 0) {
        return;
      }
      renderer.setSize(clientWidth, clientHeight, false);
      camera.aspect = clientWidth / clientHeight;
      camera.updateProjectionMatrix();
    };
    resize();

    const observer = new ResizeObserver(resize);
    observer.observe(container);

    const reduced = view.matchMedia?.('(prefers-reduced-motion: reduce)').matches ?? false;

    // Where the reader is, 0 at the top of the page and 1 a screen further on.
    let progress = 0;
    let eased = 0;
    const readProgress = () => {
      progress = Math.min(1, Math.max(0, view.scrollY / Math.max(1, view.innerHeight)));
    };
    readProgress();
    eased = progress;

    const draw = () => {
      // Scroll is the transport: the stack lifts apart and turns as the reader
      // goes down, and puts itself back together on the way up.
      eased += (progress - eased) * 0.09;
      group.rotation.y = -0.55 + eased * 1.5;
      group.rotation.x = -0.5 + eased * 0.42;
      group.position.y = eased * 0.34;
      for (const [index, stone] of stones.entries()) {
        const spread = (1 - index) * 0.3;
        stone.position.y = spread + (1 - index) * eased * 0.52;
        stone.position.x = (index - 1) * eased * 0.36;
      }
      renderer.render(scene, camera);
    };

    if (reduced) {
      // One frame, in the assembled pose, and nothing ever moves again.
      eased = 0;
      progress = 0;
      draw();
    } else {
      let frame = 0;
      let running = false;
      const tick = (time: number) => {
        // Each stone drifts on its own, slowly and at its own rate. This is the
        // only motion here not driven by scroll.
        const t = time / 1000;
        stones[0].rotation.y = Math.sin(t * 0.21) * 0.24;
        stones[1].rotation.y = Math.sin(t * 0.17 + 2.1) * 0.3;
        stones[2].rotation.y = Math.sin(t * 0.13 + 4.2) * 0.2;
        draw();
        frame = view.requestAnimationFrame(tick);
      };

      const onScroll = () => readProgress();
      view.addEventListener('scroll', onScroll, { passive: true });

      // Nothing is drawn while the hero is off screen.
      const visibility = new IntersectionObserver(
        (entries) => {
          const visible = entries.some((entry) => entry.isIntersecting);
          if (visible && !running) {
            running = true;
            frame = view.requestAnimationFrame(tick);
          } else if (!visible && running) {
            running = false;
            view.cancelAnimationFrame(frame);
          }
        },
        { threshold: 0 },
      );
      visibility.observe(container);

      this.destroyRef.onDestroy(() => {
        view.cancelAnimationFrame(frame);
        view.removeEventListener('scroll', onScroll);
        visibility.disconnect();
      });
    }

    this.destroyRef.onDestroy(() => {
      observer.disconnect();
      for (const stone of stones) {
        stone.geometry.dispose();
      }
      material.dispose();
      renderer.dispose();
      renderer.domElement.remove();
    });
  }
}

/**
 * An SVG path into a `THREE.Shape`.
 *
 * The mark's outlines are one absolute `M` and a run of relative cubics, which
 * is all this handles — deliberately. A general SVG parser would be a dependency
 * for three strings that are generated by a script in this repository, and the
 * strings are the reason it can stay this small.
 *
 * SVG's y axis points down and three.js's points up, so y is negated; both axes
 * are centred on the 64-unit viewBox and scaled to about one unit.
 */
function shapeFromPath(d: string, size = 64): THREE.Shape {
  const shape = new THREE.Shape();
  const tokens = d.match(/[a-zA-Z]|-?\d*\.?\d+/g) ?? [];
  const toX = (value: number) => (value - size / 2) / size;
  const toY = (value: number) => -(value - size / 2) / size;

  let index = 0;
  let command = '';
  let x = 0;
  let y = 0;

  while (index < tokens.length) {
    const token = tokens[index];
    if (/[a-zA-Z]/.test(token)) {
      command = token;
      index += 1;
      if (command === 'z' || command === 'Z') {
        shape.closePath();
        continue;
      }
    }
    if (command === 'M') {
      x = Number(tokens[index++]);
      y = Number(tokens[index++]);
      shape.moveTo(toX(x), toY(y));
    } else if (command === 'c') {
      const c1x = x + Number(tokens[index++]);
      const c1y = y + Number(tokens[index++]);
      const c2x = x + Number(tokens[index++]);
      const c2y = y + Number(tokens[index++]);
      const endX = x + Number(tokens[index++]);
      const endY = y + Number(tokens[index++]);
      shape.bezierCurveTo(toX(c1x), toY(c1y), toX(c2x), toY(c2y), toX(endX), toY(endY));
      x = endX;
      y = endY;
    } else {
      index += 1;
    }
  }
  return shape;
}
