import { ChangeDetectionStrategy, Component, input } from '@angular/core';

/**
 * The sloop mark: three stacked pebbles, in `currentColor`.
 *
 * The geometry is generated by `web/tools/mark.py`, which writes
 * `public/favicon.svg` from the same numbers. **Edit the script and re-run it**
 * — never these path strings, and never the favicon, or the two part company.
 *
 * Each lower pebble is drawn through a mask that subtracts the one resting on
 * it, dilated by the seam. That leaves exactly one thin transparent line per
 * contact; stroking every outline instead leaves two, and reads as five shapes.
 *
 * The masks need ids unique to the instance — the navbar renders the mark twice,
 * once upright and once as its own reflection, and two `id="mark-a"` in one
 * document would both resolve to the first.
 */
/** Instance counter, so two marks on one page cannot share a mask id. */
let seq = 0;

@Component({
  selector: 'app-mark',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <svg
      [attr.viewBox]="'0 0 64 64'"
      [attr.role]="label() ? 'img' : 'presentation'"
      [attr.aria-label]="label() || null"
      [attr.aria-hidden]="label() ? null : 'true'"
      focusable="false"
    >
      <defs>
        <mask [attr.id]="uid + '-a'" maskUnits="userSpaceOnUse" x="0" y="0" width="64" height="64">
          <rect width="64" height="64" fill="#fff" />
          <path [attr.d]="middle" fill="#000" stroke="#000" stroke-width="3.4" />
        </mask>
        <mask [attr.id]="uid + '-b'" maskUnits="userSpaceOnUse" x="0" y="0" width="64" height="64">
          <rect width="64" height="64" fill="#fff" />
          <path [attr.d]="top" fill="#000" stroke="#000" stroke-width="3.4" />
        </mask>
      </defs>
      <g fill="currentColor">
        <path [attr.d]="bottom" [attr.mask]="'url(#' + uid + '-a)'" />
        <path [attr.d]="middle" [attr.mask]="'url(#' + uid + '-b)'" />
        <path [attr.d]="top" />
      </g>
    </svg>
  `,
  styles: `
    :host {
      display: block;
    }
    svg {
      display: block;
      width: 100%;
      height: 100%;
    }
  `,
})
export class Mark {
  /** Set on the one that is the page's actual mark; left empty on decoration. */
  readonly label = input('');

  protected readonly uid = `mark-${++seq}`;

  protected readonly top =
    'M60.52 11.21c0.37 2.87 -3.72 7.12 -8.28 9.63c-4.56 2.50 -12.28 4.85 -19.07 5.40c-6.80 0.55 -16.72 -0.59 -21.70 -2.10c-4.98 -1.50 -7.88 -4.38 -8.18 -6.91c-0.30 -2.53 1.80 -5.95 6.38 -8.28c4.58 -2.33 14.36 -4.83 21.08 -5.72c6.73 -0.88 14.31 -0.92 19.27 0.41c4.96 1.33 10.13 4.70 10.50 7.57z';

  protected readonly middle =
    'M62.00 33.89c-0.22 2.57 -5.30 5.17 -10.49 6.76c-5.19 1.59 -13.90 3.22 -20.66 2.76c-6.77 -0.46 -15.20 -3.04 -19.94 -5.49c-4.74 -2.46 -8.77 -6.39 -8.52 -9.24c0.25 -2.85 4.94 -6.50 10.01 -7.86c5.08 -1.37 13.71 -1.07 20.45 -0.33c6.74 0.74 15.15 2.53 20.01 4.77c4.86 2.24 9.37 6.08 9.15 8.64z';

  protected readonly bottom =
    'M59.51 49.00c0.06 2.78 -1.42 6.80 -5.96 8.76c-4.54 1.96 -14.49 2.77 -21.27 3.02c-6.78 0.25 -14.35 0.11 -19.39 -1.52c-5.05 -1.63 -10.63 -5.53 -10.89 -8.25c-0.26 -2.72 4.39 -5.84 9.30 -8.06c4.91 -2.23 13.19 -4.98 20.17 -5.29c6.98 -0.31 17.03 1.53 21.70 3.42c4.67 1.89 6.27 5.14 6.34 7.92z';
}
